---
apiVersion: v1
kind: Services
metadata:
    name: nginx-service-dm
    labels:
       app: nginx
spec:
  type: LoadBalancer
  ports:
    - name: http-port
      protocol: Tcp
      port: 4523
      targetPort: 80
  selector:
     app: sample-daemonset
    
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: sample-daemonset
spec:
  selector:
    matchLabels:
      app: sample-daemon
  template:
    metadata:
      labels:
        app: sample-daemon
    spec:
      containers:
      - name: sample-daemon-container
        image: nginx
        ports:
         - containerPort: 80
        resources:
          requests:
            cpu: "150m"
            memory: "200Mi"
          limits:
            cpu: "200m"
            memory: "300Mi"
