---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: app-daemon
  labels:
    app: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    matadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapps
          image: nginx
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: 200Mi
              cpu: 150m
            limits:
              memory: 300Mi
              cpu: 200m
